# Generated by Django 3.1.3 on 2020-11-28 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20201127_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='forum.section'),
            preserve_default=False,
        ),
    ]
