# Generated by Django 3.1.3 on 2020-11-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20201128_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posting',
            options={'ordering': ['-update_time']},
        ),
    ]
