# Generated by Django 3.1.4 on 2020-12-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_comment_append_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='append_file',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
