# Generated by Django 3.1.4 on 2020-12-05 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20201205_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='append_file',
        ),
    ]
