# Generated by Django 3.1.4 on 2020-12-05 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examine', '0001_initial'),
        ('forum', '0011_comment_append_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='examine.examine'),
        ),
        migrations.AddField(
            model_name='posting',
            name='ex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='examine.examine'),
        ),
    ]
