# Generated by Django 3.1.4 on 2020-12-05 03:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('examine', '0001_initial'),
        ('forum', '0012_auto_20201205_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ex',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='examine.examine'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posting',
            name='ex',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='examine.examine'),
            preserve_default=False,
        ),
    ]
