# Generated by Django 3.1.4 on 2020-12-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tp', models.CharField(choices=[('jpg', '.jpg'), ('png', '.png'), ('gif', '.gif'), ('bmp', '.bmp'), ('jpeg', '.jpeg')], max_length=4)),
                ('origin_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
