# Generated by Django 3.1.4 on 2020-12-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worddata',
            name='groop',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
