# Generated by Django 3.1.4 on 2020-12-15 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_report'),
        ('words', '0002_worddata_groop'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_created=True)),
                ('groop', models.CharField(max_length=10)),
                ('num', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
