# Generated by Django 3.1.4 on 2020-12-15 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_worddata_md5'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worddata',
            options={'ordering': ['md5']},
        ),
    ]
