# Generated by Django 3.1.4 on 2020-12-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_auto_20201215_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordplan',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
