# Generated by Django 3.1.3 on 2020-11-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('hits', models.IntegerField(default=0)),
                ('number_of_likes', models.IntegerField(default=0)),
                ('share', models.BooleanField(default=False)),
                ('abstract', models.CharField(default='暂无简介，进来看看吧', max_length=100)),
            ],
            options={
                'ordering': ['-pub_time'],
            },
        ),
    ]
