# Generated by Django 3.1.4 on 2020-12-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tp', models.CharField(choices=[('SU', 'superUser'), ('NU', 'normalUser'), ('BL', 'userInBlackList')], max_length=2)),
            ],
        ),
    ]
