# Generated by Django 3.1.3 on 2020-11-27 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('nickname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('usertype', models.CharField(choices=[('SU', 'superUser'), ('NU', 'normalUser'), ('BL', 'userInBlackList')], max_length=2)),
                ('credit', models.IntegerField(default=100)),
                ('score', models.IntegerField(default=0)),
                ('face', models.FileField(blank=True, null=True, upload_to='img')),
                ('friend', models.ManyToManyField(related_name='_user_friend_+', to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Visited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
