# Generated by Django 3.1.3 on 2020-12-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend_apply',
            field=models.ManyToManyField(related_name='_user_friend_apply_+', to='user.User'),
        ),
    ]
