# Generated by Django 3.1.3 on 2020-12-01 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_friend_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friend',
        ),
        migrations.AddField(
            model_name='user',
            name='friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='user.user'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='friend_apply',
        ),
        migrations.AddField(
            model_name='user',
            name='friend_apply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apply', to='user.user'),
        ),
    ]
