# Generated by Django 3.1.3 on 2020-12-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201201_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friend',
        ),
        migrations.AddField(
            model_name='user',
            name='friend',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_friend_+', to='user.User'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='friend_apply',
        ),
        migrations.AddField(
            model_name='user',
            name='friend_apply',
            field=models.ManyToManyField(blank=True, null=True, related_name='_user_friend_apply_+', to='user.User'),
        ),
    ]
