# Generated by Django 3.1.3 on 2020-12-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201201_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friend',
            field=models.ManyToManyField(related_name='_user_friend_+', to='user.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friend_apply',
            field=models.ManyToManyField(related_name='_user_friend_apply_+', to='user.User'),
        ),
    ]
