# Generated by Django 3.1.4 on 2020-12-02 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201201_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friend_apply',
        ),
    ]
