# Generated by Django 3.1.4 on 2020-12-02 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_friend_apply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('say', models.CharField(max_length=100)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='user.user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='user.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='friend_apply',
            field=models.ManyToManyField(related_name='_user_friend_apply_+', through='user.Apply', to='user.User'),
        ),
    ]
