# Generated by Django 3.1.4 on 2020-12-05 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examine', '0001_initial'),
        ('user', '0008_auto_20201202_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='examine.examine'),
        ),
    ]
