# Generated by Django 3.1.4 on 2020-12-05 03:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('examine', '0001_initial'),
        ('user', '0009_user_ex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ex',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='examine.examine'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_logined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_signed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
