# Generated by Django 3.1.3 on 2020-11-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_auto_20201130_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('urlname', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='files',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
